name: Linux Cmake Build

on:
  push:
  pull_request:

jobs:
  linux-amd64-cmake-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y bc cmake
      - name: Build BLASFEO
        run: |
          git clone https://github.com/giaf/blasfeo
          mkdir blasfeo/build
          cd blasfeo/build
          cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/blasfeo ..
          make -j 4
          make install
      - name: Build HPIPM with CMake and run test
        run: |
          mkdir build
          cd build
          cmake -DBLASFEO_PATH=${{ github.workspace }}/blasfeo ..
          make -j 4
          cd test_problems
          ./d_ocp_qp